### ISSUE TITLE
Node.js `corepack enable` fails within Flox environments

### ISSUE THREAD

**Issue by tallpants** [flox/flox#2486]
**Describe the bug:**
[Corepack](https://github.com/nodejs/corepack) is distributed by default with Node.js and enables use of package managers like Yarn and pnpm without having to install them explicitly.

Running `corepack enable` within a Flox environment (either in the `on-activate` hook or in the shell after running `flox activate`) fails with an EACCESS error (at least on macOS)

**Steps to reproduce:**
1. `flox init`
2. `flox install nodejs`
3. `flox activate`
4. `corepack enable`

Result:

```
Internal Error: EACCES: permission denied, symlink '../../f0lm95g31vpknr8jj9xw53cx2rqly2nm-nodejs-20.18.1/lib/node_modules/corepack/dist/pnpm.js' -> '/nix/store/v23dh207wg00kr5wnl477ysxz1w1d6x1-environment-develop/bin/pnpm'
    at async Object.symlink (node:internal/fs/promises:1000:10)
    at async EnableCommand.generatePosixLink (/nix/store/f0lm95g31vpknr8jj9xw53cx2rqly2nm-nodejs-20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:22608:5)
    at async Promise.all (index 0)
    at async EnableCommand.execute (/nix/store/f0lm95g31vpknr8jj9xw53cx2rqly2nm-nodejs-20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:22595:5)
    at async EnableCommand.validateAndExecute (/nix/store/f0lm95g31vpknr8jj9xw53cx2rqly2nm-nodejs-20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:19835:22)
    at async _Cli.run (/nix/store/f0lm95g31vpknr8jj9xw53cx2rqly2nm-nodejs-20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:20772:18)
    at async Object.runMain (/nix/store/f0lm95g31vpknr8jj9xw53cx2rqly2nm-nodejs-20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23091:19)
```

Expected:
No output and package managers (`yarn` and `pnpm`) available on environment based on version specific in the `packageManager` field in `package.json`.

**Flox Version:**
1.3.6

**`uname -a` output:**

`Darwin Adithyas-MacBook-Pro.local 24.2.0 Darwin Kernel Version 24.2.0: Fri Nov 15 19:28:48 PST 2024; root:xnu-11215.61.3~1/RELEASE_ARM64_T6000 arm64`

**Comment by tallpants** [comment]
Want to point that it's easy to get around this by not using Corepack at all and installing the package manager you want with Flox itself, but wanted to point out that this is an explicit feature of Node.js itself that fails within Flox.

**Comment by tallpants** [comment]
Seems like the solution here is to install corepack itself from Nix: https://nixos.org/manual/nixpkgs/stable/#javascript-corepack

So it doesn't seem like a bug, but may be worth documenting nonetheless. Please feel free to close this issue if you feel like it's not necessary to document this either. Sorry for the noise!

**Comment by stahnma** [comment]
@tallpants It's not noise. This might be something we can move upstream into nixpkgs as corepack as provided by `nodejs` package is pretty broken and expected to be part of `nodejs`. @tomberek can you confirm this and see about upstream fix for node?

**Comment by mkenigs** [comment]
> [@tallpants](https://github.com/tallpants) It's not noise. This might be something we can move upstream into nixpkgs as corepack as provided by `nodejs` package is pretty broken and expected to be part of `nodejs`. [@tomberek](https://github.com/tomberek) can you confirm this and see about upstream fix for node?

The suggestion is that Flox provided `corepack` should be in `PATH` when Flox provided `nodejs` is installed

**Comment by zmitchell** [comment]
> The suggestion

Are you saying that this is the suggestion from upstream, from @tomberek, or that we should install `corepack` when we install `nodejs`? I'm having trouble parsing this response.

**Comment by zmitchell** [comment]
I think there is some confusion in the responses to this ticket. The original issue looks like `corepack` failing because it's attempting to create a symlink in the Nix store, which is read-only (for good reason). `corepack` is already in `PATH`, which you can see in the original error because it's `corepack` itself that's failing:
```
at async Object.runMain (/nix/store/f0lm95g31vpknr8jj9xw53cx2rqly2nm-nodejs-20.18.1/lib/node_modules/corepack/dist/lib/corepack.cjs:23091:19)
```

So, I don't think there's anything to do here other than to do what @tallpants recommended earlier and just install the package manager you're looking for via Flox in the first place.
